#!/usr/bin/env bash
# setup-mac.sh — Antigravity Quota Tracker
#
# Creates a shell wrapper that launches Antigravity with the CDP debug flag.
# Run this once from the project root:
#   bash scripts/setup-mac.sh
#
# What it does:
#   1. Finds Antigravity.app in /Applications or ~/Applications
#   2. Creates ~/bin/antigravity-debug wrapper script
#   3. Adds ~/bin to PATH in your shell profile (if needed)
#
# After running, launch Antigravity via: antigravity-debug
# (or via the Automator app — see below for manual steps)

set -euo pipefail

CDP_PORT="${CDP_PORT:-9222}"
WRAPPER="$HOME/bin/antigravity-debug"

echo ""
echo "Antigravity Quota Tracker — macOS Setup"
echo ""

# ── Find Antigravity.app ──────────────────────────────────────────────────────

APP_PATH=""
for candidate in \
    "/Applications/Antigravity IDE.app" \
    "/Applications/Antigravity.app" \
    "$HOME/Applications/Antigravity IDE.app" \
    "$HOME/Applications/Antigravity.app"
do
    if [ -d "$candidate" ]; then
        APP_PATH="$candidate"
        break
    fi
done

if [ -z "$APP_PATH" ]; then
    echo "⚠  Antigravity not found in /Applications or ~/Applications."
    echo "   Edit APP_PATH in this script or set it in your environment."
    echo "   Continuing to create a template wrapper..."
    APP_PATH="/Applications/Antigravity IDE.app"
fi

echo "Using: $APP_PATH"

# ── Create ~/bin if needed ────────────────────────────────────────────────────

mkdir -p "$HOME/bin"

# ── Write wrapper script ───────────────────────────────────────────────────────

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# antigravity-debug — launches Antigravity with CDP remote debugging enabled.
# Generated by scripts/setup-mac.sh — edit APP_PATH below if needed.
set -euo pipefail

APP_PATH="${APP_PATH}"
CDP_PORT="${CDP_PORT}"

exec open -a "\$APP_PATH" --args --remote-debugging-port=\$CDP_PORT "\$@"
EOF

chmod +x "$WRAPPER"
echo "✓ Created wrapper: $WRAPPER"

# ── Add ~/bin to PATH ─────────────────────────────────────────────────────────

for profile in "$HOME/.zshrc" "$HOME/.bash_profile" "$HOME/.bashrc"; do
    if [ -f "$profile" ] && ! grep -q 'HOME/bin' "$profile" 2>/dev/null; then
        echo "" >> "$profile"
        echo '# Added by Antigravity Quota Tracker setup' >> "$profile"
        echo 'export PATH="$HOME/bin:$PATH"' >> "$profile"
        echo "✓ Added ~/bin to PATH in $profile"
        break
    fi
done

echo ""
echo "Setup complete!"
echo ""
echo "Launch Antigravity with CDP debugging:"
echo "  antigravity-debug"
echo ""
echo "Then start the notifier:"
echo "  python notifier/notifier.py"
echo ""

# ── Manual Automator steps (printed for reference) ───────────────────────────
# Creating an Automator Application that launches with custom arguments is
# not fully scriptable without GUI automation (osascript can open Automator
# but cannot reliably drive its workflow editor).  Steps are documented here
# for users who prefer a double-clickable app launcher.

echo "─────────────────────────────────────────────────────────────────────"
echo "Optional: Create an Automator launcher (double-clickable .app)"
echo ""
echo "  1. Open Automator → New Document → Application"
echo "  2. Add action: Utilities → Run Shell Script"
echo "  3. Paste this command:"
echo "       open -a '${APP_PATH}' --args --remote-debugging-port=${CDP_PORT}"
echo "  4. Save as: ~/Desktop/Antigravity Debug.app"
echo ""
echo "  This creates a .app you can double-click to launch Antigravity"
echo "  with the CDP flag, equivalent to running 'antigravity-debug'."
echo "─────────────────────────────────────────────────────────────────────"
